/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio.pkg4;

import javax.swing.JOptionPane;

/**
 *
 * @author Payares
 */
public class interfazgrafica4 extends javax.swing.JFrame {

    /**
     * Creates new form interfazgrafica4
     */
    public interfazgrafica4() {
        initComponents();
    }
    public void borrar(){
         cfinal.setText("");
        metros.setText("");
        cuotainicio.setText("");
        metros.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        metros = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cuotainicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cfinal = new javax.swing.JTextField();
        cmbcalcular = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setText("Calcular valor del terreno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setText("cantidad de metros cuadrados:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        metros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metrosActionPerformed(evt);
            }
        });
        metros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                metrosKeyTyped(evt);
            }
        });
        jPanel1.add(metros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 160, -1));

        jLabel3.setText("Cuota inicial del terreno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        cuotainicio.setAutoscrolls(false);
        cuotainicio.setEnabled(false);
        jPanel1.add(cuotainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        jLabel4.setText("12 cuotas finales:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        cfinal.setAutoscrolls(false);
        cfinal.setEnabled(false);
        jPanel1.add(cfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, -1));

        cmbcalcular.setText("Calcular");
        cmbcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmbcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        cmbBorrar.setText("Borrar");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcalcularActionPerformed
        // TODO add your handling code here:
        String res1,res2;
        double n1,n2;
        double op,op1,op2,op3;
        n1 = Double.parseDouble(metros.getText());
        
        
        if (n1 == 0 ){
             JOptionPane.showMessageDialog(this,"Digita  un numero distinto a cero(0)","Error",JOptionPane.ERROR_MESSAGE);
             borrar();
            metros.requestFocusInWindow();
        }
            else{
                  op= (n1*80000) ; 
                    op1=op*0.35;
                    op3=op-op1;
                    op2=op3/12;
                    
                     res1 = String.valueOf(op1);
                     res2=String.valueOf(op2);
                   cuotainicio.setText(res1);
                   cfinal.setText(res2);
                    }
        
    }//GEN-LAST:event_cmbcalcularActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void metrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metrosActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_metrosActionPerformed

    private void metrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_metrosKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();
          }
    }//GEN-LAST:event_metrosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazgrafica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazgrafica4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cfinal;
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbcalcular;
    private javax.swing.JTextField cuotainicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField metros;
    // End of variables declaration//GEN-END:variables
}
